GET http://localhost:4657/game/flag/8308687e-a3eb-429d-a915-1805b7b14001/5/0
Accept: application/json

###
GET http://localhost:4657/game/draw/8308687e-a3eb-429d-a915-1805b7b14001
Accept: application/text

###
GET http://localhost:4657/game/click/8308687e-a3eb-429d-a915-1805b7b14001/0/1
Accept: application/json

###
GET http://localhost:4657/game/status/8a371623-78f3-4ac9-8f57-3d53d6ea8ca6
Accept: application/json

###
GET http://localhost:4657/game/start/6/6
Accept: application/json

###
GET http://localhost:4657/status
Accept: application/json

###
